# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: parnikcode/website:latest
        ports:
        - containerPort: 80
